name: Kernel Compilation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up build environment
        run: |
          sudo apt update -y
          sudo apt install -y libncurses5-dev bc bison flex make gcc g++ git python3 zip unzip

      - name: Set environment variable
        run: |
          echo "BUILD_KERNEL_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Compile Kernel
        run: |
          bash build.sh

      - name: Build External Module
        run: |
          bash build_external_module.sh

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KernelSM-A047F-${{ github.event.inputs.tag }}
          path: build/*.tar

      - name: Upload Module Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExternalModuleSM-A047F-${{ github.event.inputs.tag }}
          path: build/modules/*.ko

      - name: Create or update release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag }}
          name: "KernelSM-A047F-${{ github.event.inputs.tag }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/*.tar,build/modules/*.ko"
          allowUpdates: true
          replacesArtifacts: true
          body: "Commit SHA: ${{ github.sha }}"
